name: build_job

on:
  workflow_call:
    inputs:
      test_input1:
        required: true
        type: boolean
        default: false


jobs:
  build_job:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - name: echo input value
        run: echo ${{ github.event.inputs.test_input1 }}
