name: build_job

on:
  workflow_dispatch: 
  workflow_call:
    inputs:
      test_input1:
        required: true
        type: boolean
        default: false


jobs:
  build_job:
    runs-on: ubuntu-20.04
    timeout-minutes: 180
    steps:
      - name: echo input value
        run: echo ${{ inputs.test_input1 }}
      - name: echo type
        run: echo typeof ${{ inputs.test_input1 }}
