name: demo input workflow

on:
  workflow_dispatch:
    inputs:
      test_input1:
        description: test input variables
        type: boolean
        default: true


jobs:
  job1:
    uses: Melsoft-Games/workflow-input-demo/.github/workflows/build_job.yml@master
    with:
      test_input1: ${{ github.event.inputs.test_input1 }}
